# docker-compose.yml

version: "3"

services:
  mariadb:
    image: mariadb
    container_name: go_pos_mariadb
    restart: on-failure
    volumes:
      - ./infra/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: homestod
      MYSQL_DATABASE: gopos
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    networks:
      - gonet

  app:
    build:
      context: .
    volumes:
      - ./:/go/src/go-pos
    image: gopos
    container_name: go-pos
    restart: on-failure
    ports:
      - 7000:7000
    environment:
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: gopos
    networks:
      - gonet

networks:
  gonet:
    driver: bridge
